name: "team-builder"

services:
  api:
    build:
      context: ./API
    image: "team-builder-api"
    environment:
      - PGHOST=db
      - PORT=${API_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
      - FRONTEND_PORT=${FRONTEND_PORT}
    ports:
      - ${API_PORT}:8080
    depends_on:
      db:
        condition: service_healthy
    
  frontend:
    build:
      context: ./frontend
    image: "team-builder-frontend"
    ports:
      - ${FRONTEND_PORT}:8080
    depends_on:
      api:
        condition: service_started      

  db:
    image: postgres:17.2
    restart: always
    user: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGPORT=${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
    name: "team-builder-db-data"